config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'frontend/contents#show'

  # To separate the backend from public sites, we wrap it with a constraint
  # that only allows access via a pre-configured 'backend_host'. See
  # config/bold.yml.sample for how to set that.
  #
  # Besides making the backend accessible exclusively via a dedicated hostname
  # (i.e. cms.yoursite.com) this has the nice side effect of freeing up the URL
  # name space for your sites so you dont have to worry about collisions with
  # Bold's backend.
  #
  # If you don't care about this kind of separation, set backend_host to your
  # sites public hostname. Your site will then redirect requests to backend
  # paths to Bold's login page instead of rendering the 404 page.
  #
  constraints Bold::Routes::BackendConstraint.new do

    devise_for :users

    # initial setup
    # the constraint hides these routes once at least one site is present.
    constraints Bold::Routes::SetupConstraint.new do
      namespace :setup do
        root 'users#new', as: 'root'
        resource :user, only: %i(new create)
        resource :site, only: %i(new create)
      end
    end

    # backend
    namespace :bold do

      root to: 'sites#index', as: :root

      resource :profile, only: %i(edit update edit_password update_password edit_email update_email) do
        collection do
          get :edit_email, :edit_password
          put :update_email, :update_password
        end
      end


      resources :sites, only: %i(show index)  do

        namespace :activity do
          resources :stats, only: :index do
            collection do
              get :visits_per_day
            end
          end
          resources :comments, shallow: true, only: %i(index destroy) do
            member do
              patch :restore, :mark_spam, :mark_ham, :approve, :unapprove
            end
            collection do
              delete :destroy_spam
            end
          end
        end

        resources :asset_links, only: :new

        resources :assets, shallow: true do
          collection do
            post :create_from_url
            get :gallery
            delete :bulk_destroy
          end
          member do
            post :pick
          end
        end
        resources :pages, shallow: true do
          member do
            get :diff, :change_template
            patch :update_template
            delete :delete_draft
          end
        end
        resources :posts, shallow: true do
          member do
            get :diff, :change_template
            patch :update_template
            delete :delete_draft
          end
        end

        # Site Settings
        namespace :settings do
          root 'settings#edit', as: 'root'

          resources :backups, only: %i(index create)
          resources :categories, shallow: true
          resources :tags, shallow: true, only: %i(index edit update destroy)

          resources :navigations, shallow: true, only: %i(index create update destroy) do
            collection{ put :sort }
          end

          resources :plugins, only: %i(index edit update enable destroy) do
            member{ put :enable }
          end

          resource :settings, only: %i(edit update favicon set_favicon) do
            member do
              get :favicon
              get :logo
            end
          end

          resource :html_snippet, only: %i(edit update)

          resources :site_users do
            member do
              put :resend_invitation
              delete :revoke_invitation
            end
          end

          resources :themes, only: %i(index edit update enable) do
            member{ put :enable }
          end
        end

        post 'undo/:id' => 'undo#create', as: :undo
      end

    end


    # global admin
    namespace :admin do

      resources :sites

      resources :users do
        collection do
          get :invited
          get :locked
        end
        member do
          put :lock
          put :unlock
          put :reset_password
        end
        resources :site_users, only: %i(new create edit update destroy)
      end

      resources :invitations, only: %i( index new create update destroy )

    end

  end # of BackendConstraint


  # Set up theme and plugin routes
  # While themes and plugins could just define their own routes via their own
  # config/routes.rb, these would end up after the catch all below and thus
  # never be reached. Instead, declare your routes when registering the
  # extension.
  Bold::Plugin.install_routes! self
  Bold::Theme.install_routes! self

  mount Ahoy::Engine => "/ahoy"

  # Frontend routes

  # retina support
  get 'displayconfig' => 'frontend/assets#display_config', as: :display_config

  # Sitemap
  get 'sitemap.xml' => 'frontend/sitemaps#show', as: :sitemap, defaults: { format: :xml }

  # site specific css / js
  get 'site' => 'frontend/site_contents#show', as: :site_content

  # Favicon
  get 'favicon.ico' => 'frontend/assets#favicon', as: :favicon

  # Assets
  get 'files/inline/:id(/:version)'    => 'frontend/assets#show',     as: :file
  get 'files/:id(/:version)/:filename' => 'frontend/assets#download', as: :download


  # Posts by Author
  get 'authors/:author' => 'frontend/contents#author', as: :author_posts, author: /.+/

  # redirect requests with single-digit months to 0x month format
  # to avoid duplicate content penalties
  get ':year/:month/*slug',
    constraints: { year: /\d{4}/, month: /\d/ },
    to: redirect('/%{year}/0%{month}/%{slug}')

  # Archive
  constraints year: /\d{4}/, month: /\d\d/ do
    get ':year(/:month)'      => 'frontend/contents#archive', as: :archive
  end

  # Contact message creation
  post 'contact/*path' => 'frontend/contact_messages#create', as: :contact_messages, format: false

  # Pages, Posts, Tags, Categories
  get  '*path' => 'frontend/contents#show',   as: :content, format: false
  # Comment creation
  post '*path' => 'frontend/comments#create', as: :comments, format: false

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/controllers/bold/activity/comments_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold::Activity
  class CommentsController < SiteController
    prepend_before_action :set_object, except: %i(index destroy_spam)
    site_object :object

    def index
      @comment_search = CommentSearch.new search_params
      @postings = @comment_search.search(current_site.visitor_postings.includes(:content)).
        order('created_at DESC').page(params[:page]).per(20)
      @unread_items = UnreadItemCache.new(current_site, current_user, @postings)
      @unread_items.mark_all_read!
    end

    def approve
      @object.approved!
      render 'update'
    end

    def unapprove
      @object.pending!
      render 'update'
    end

    def mark_ham
      memento do
        ReportHam.call @object
      end
      undo_with 'update_comment'
      flash[:notice] = 'bold.comment.ham'
      render 'update'
    end

    def mark_spam
      memento undo_template: 'restore_comment' do
        ReportSpam.call @object
      end
      flash.now[:notice] = 'bold.comment.spam'
      render 'destroy'
    end

    def destroy
      memento undo_template: 'restore_comment' do
        DeletePosting.call @object
      end
      flash.now[:notice] = 'bold.comment.deleted'
    end

    def destroy_spam
      current_site.spam.delete
      flash[:notice] = 'bold.comment.spam_deleted'
      redirect_to bold_site_activity_comments_path(current_site)
    end

    private

    def set_object
      @object = VisitorPosting.existing.find params[:id]
    end

    def search_params
      if params[:comment_search].present?
        params[:comment_search].permit :status, :query
      elsif current_site.comments.pending.any?
        { status: 'pending' }
      else
        {}
      end
    end

  end
end

app/controllers/bold/activity/stats_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold::Activity
  class StatsController < SiteController

    def index
      @stats = Bold::Stats::Ahoy.for time_frame: time_frame_param, site: current_site
    end

    def visits_per_day
      render json: Bold::Stats::Ahoy.for(site: current_site,
                                         time_frame: time_frame_param).daily_visits.data
    end

    private

    def time_frame_param
      (params[:time_frame].presence || :month).to_sym
    end
  end
end

app/controllers/bold/asset_links_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold
  class AssetLinksController < SiteController
    helper 'bold/assets'

    decorate_assigned :assets, with: 'Bold::AssetsDecorator'

    # TODO file selection mode for downloads
    # TODO search as you type to filter asset list
    def new
      @assets = current_site.assets.images.order('created_at DESC').page(params[:page]).per(16)
      @image_versions = current_site.image_versions
      render layout: false
    end

  end
end

app/controllers/bold/assets_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold
  class AssetsController < SiteController
    rescue_from ActionController::MissingFile, with: :handle_missing_file

    prepend_before_action :find_asset, only: %i(pick edit update show destroy)
    site_object :asset

    decorate_assigned :asset, with: 'Bold::AssetDecorator'


    def index
      @asset_search = AssetSearch.new asset_search_params
      assets = current_site.assets.order('created_at DESC').page(params[:page]).per(18)
      @assets = @asset_search.present? ? @asset_search.search(assets) : assets
    end

    def new
      @source = params[:source] || 'upload'
      head 404 and return unless valid_source? @source
    end

    BUILTIN_SOURCES = %w(upload url).freeze
    def valid_source?(source)
      BUILTIN_SOURCES.include? source
    end

    def pick
    end

    def edit
    end

    def update
      @success = @asset.update_attributes(asset_params)
    end

    def show
      @asset.ensure_version! params[:version]
      send_file @asset.diskfile_path(params[:version]), disposition: :inline
    end

    def create_from_url
      @asset = current_site.assets.build new_asset_params(key: :remote_file_url)

      if @asset.file.present? and CreateAsset.call(@asset)
        redirect_to new_bold_site_asset_url(current_site, source: 'url'), notice: 'bold.assets.from_url.success'
      else
        @source = 'url'
        flash[:alert] = 'bold.assets.from_url.failure'
        render 'new'
      end
    end

    def create
      @asset = current_site.assets.build new_asset_params
      if CreateAsset.call(@asset)
        respond_to do |format|
          format.html {
            render :json => [@asset.to_jq_upload].to_json,
            :content_type => 'text/html',
            :layout => false
          }
          format.json {
            render :json => { :files => [@asset.to_jq_upload] }
          }
        end
      else
        render :json => [{:error => "otherFailure"}], :status => 304
      end
    end

    def destroy
      @asset.destroy
      respond_to do |format|
        format.json { render json: true }
        format.html { redirect_to bold_site_assets_path(current_site) }
      end
    end

    def bulk_destroy
      @ids = params[:ids].to_s.split(',').reject(&:blank?)
      current_site.assets.where(id: @ids).destroy_all
    end

    private

    def asset_search_params
      params[:asset_search].permit :query, :content_type if params[:asset_search]
    end

    def find_asset
      @asset = Asset.find params[:id]
    end

    def asset_params
      params.require(:asset).permit :file, :title, :caption, :tag_list, :attribution, :original_url, :remote_file_url
    end

    def new_asset_params(key: :file)
      params.require(:asset).tap do |attributes|
        if key == :file
          attributes[:file] = attributes[:file].first if Array === attributes[:file]
        end
        #attributes.delete(:content_id) if attributes[:content_id].blank?
      #end.permit(:file, :content_id, :remote_file_url)
      end.permit(key)
    end

  end
end

app/controllers/bold/pages_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold
  class PagesController < SiteController
    include ContentEditing

    def update
      save_page
    end

    def create
      @content = current_site.pages.build
      save_page
    end

    private

    def save_page
      @content.attributes = content_params
      result = SaveContent.call(
        @content,
        publish: (params[:publish] || params[:do_publish].present?)
      )
      flash[result.message_severity] = result.message

      respond_to do |format|

        format.html do
          if result.saved?
            redirect_to edit_bold_page_path @content
          else
            render @content.new_record? ? 'new' : 'edit'
          end
        end

        format.js do
          if params[:go_back].present?
            @back_to = bold_site_pages_url(current_site)
          end
        end
      end
    end

    def edit_url(content = @content)
      edit_bold_page_path(content)
    end

    def find_content
      @content = Page.existing.find params[:id]
    end

    def collection
      coll = current_site.pages.existing.order('slug ASC')
      @content_search.present? ? @content_search.search(coll) : coll
    end

    def content_params
      params.require(:content).permit(:title, :body, :slug, :post_date_str, :template, :meta_title, :meta_description, template_field_values: @content.get_template.fields)
    end

    def content_search_params
      params[:content_search].permit :status, :query if params[:content_search]
    end

  end
end

app/views/bold/content/_change_template.html.haml
.modal-dialog.modal-sm
  .modal-content
    = simple_form_for @content, url: { action: 'update_template' } do |f|
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4= t '.heading'

      .modal-body{style: 'min-height: 100px;'}
        = f.input :template, required: false, collection: current_site.theme.templates.values, value_method: :name, label_method: :pretty_name, include_blank: false, input_html: { class: 'input-sm' }

      .modal-footer
        = button '.save', 'success btn-sm save', name: 'save'

app/views/bold/content/_create.js.erb
window.location.href = '<%= escape_javascript @redirect_url %>';

app/views/bold/content/_delete_or_unpublish.html.haml
- if @content.published?
  = link_with_icon :'eye-close', t('.unpublish'), (Post === @content ? bold_post_path(@content) : bold_page_path(@content)), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: t('.confirm_unpublish', title: @content.title)}, tabindex: 112
- elsif @content.persisted?
  = link_with_icon :trash, t('.delete'), (Post === @content ? bold_post_path(@content) : bold_page_path(@content)), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: t('.confirm_delete', title: @content.title)}, tabindex: 112

app/views/bold/content/_diff.html.haml
.modal-dialog.modal-lg.big
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h4#modal-label.modal-title= t '.heading', title: @content.title

    .modal-body
      - if @diff.present?
        =raw @diff
      - else
        = t '.no_data'

    .modal-footer
      = link_with_icon :trash, t('.delete_draft'), (Post === @content ? delete_draft_bold_post_path(@content) : delete_draft_bold_page_path(@content)), method: :delete, class: 'btn btn-danger btn-sm'

app/views/bold/content/_edit.html.haml
- content_for :container_class, 'absolute'

#markdown-help.modal.fade{ tabindex:"-1", role:"dialog", aria: { labelledby:"helpHeader", hidden:"true" } }
  = render 'bold/content/markdown_help'


= simple_form_for @content, url: content_form_url(@content), html: { id: 'bold-editor-form', role: 'form', remote: true } do |f|
  .row

    #editor-wrapper.col-xs-12.col-sm-8.col-md-7
      = f.text_field :title, placeholder:t('.title_plh'), class: 'title', id: 'title-field', autofocus: ('autofocus' if @content.new_record?)

      - if @content.get_template.body?
        .toolbar
          = link_to icon(:'question-sign'), '#', data: { toggle: 'modal', target: '#markdown-help' }, tabindex: 999
          .pull-right
            %span.group
              = link_to icon(:header), '#', id: 'title-caps', title: t('.toolbar.capitalize'), tabindex: 999

            %span.group
              = link_to icon(:link), '#', id: 'link', title: t('.toolbar.link'), tabindex: 999
              = link_to icon(:picture), new_bold_site_asset_link_path(current_site), remote: true, id: 'picture', title: t('.toolbar.image'), tabindex: 999

            %span.group
              = link_to icon(:fullscreen), '#', id: 'zen-mode', title: t('.toolbar.zenmode'), tabindex: 999


        ~ f.text_area :body, class: 'ace', data: { container: 'editor', vimmode: current_user.vim_mode? }
        #editor
      - else
        %p= t'.info_no_body', template: @content.template

    #editor-sidebar.independent-scroll.col-xs-12.col-sm-4.col-md-5
      = render 'bold/content/editor_sidebar', f: f

app/views/bold/content/_editor_sidebar.html.haml
.row
  .col-xs-12.col-sm-10.col-sm-offset-1

    .actions

      = button '.save', 'success btn-sm save', name: 'save', tabindex: 110, icon: :save, disabled: true
      = button '.publish', "primary btn-sm save #{@content.has_unpublished_changes? ? 'has-draft' : 'has-no-draft'}", name: 'publish', tabindex: 111, icon: :globe, disabled: !@content.has_unpublished_changes?

      #other-actions.pull-right
        = render partial: 'bold/content/delete_or_unpublish'

    %p#publish-status
      = render partial: 'bold/content/publish_status', locals: { content: @content }

    - unless @content.published?
      #pubdate-field
        %p
          = f.input :post_date_str, as: :string, placeholder: t('.post_date_str_plh'), input_html: { tabindex: 105 }


    = f.input :slug, wrapper_html: { class: 'content-slug' }, input_html: { data: { locked: @content.slug.present? }, tabindex: 100, class: 'content-slug input-sm' }, disabled: @content.published?

    - if current_site.categories.any? && @content.is_a?(Post)
      = f.input :category_id, collection: current_site.categories, label_method: :name, value_method: :id

    = f.input :tag_list, as: :text, input_html: { rows: 2, class: 'input-sm', tabindex: 101 } if Post === @content
    = f.input :meta_title, as: :string, input_html: { class: 'input-sm', placeholder: t('.meta_title_plh'), tabindex: 102 }
    = f.input :meta_description, as: :text, wrapper_html: { id: 'meta_description_wrapper' }, input_html: { class: 'input-sm', rows: 2, tabindex: 103 }, hint: t('.meta_description_remaining_chars')

    - if @content.new_record?
      = f.input :template, required: false, collection: current_site.theme.templates.values, value_method: :name, label_method: :pretty_name, include_blank: false, input_html: { class: 'input-sm', tabindex: 104 }
    - else
      .form-group
        %label.control-label= t'.template'
        %p.small.form-control-static
          = link_to t('.change_template'), { action: 'change_template' }, data: { ondirty: 'Please save your changes first before changing the template.' }, id: 'change-template', remote: true, class: 'btn btn-default btn-sm pull-right'
          = @content.get_template.pretty_name

    - if @content.has_template_fields?
      = f.fields_for :template_field_values, f.object, builder: Bold::Views::TemplateFieldsFormBuilder do |f|
        = render @content.template_fields_partial, f: f

app/views/bold/content/_linked_assets.html.haml
.panel.panel-default
  .panel-body
    #linked-assets
      = render 'bold/asset_links/index'

app/views/bold/content/_markdown_help.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button{type:"button", class:"close", data: { dismiss:"modal" }, aria: { label:"Close" }}
        %span{aria:{hidden:"true"}} &times;
      %h4#helpHeader.modal-title= t'.heading'

    .modal-body

      %table.table.no-borders
        %tbody
          %tr
            %td
              %strong Strong Emphasis
            %td **Strong Emphasis**
          %tr
            %td
              %em Light Emphasis
            %td *Light Emphasis*
          %tr
            %td
              %code Inline code
            %td `Inline code`
          %tr
            %td
              %a{href:"https://trybold.org"} External Link
            %td [Link](https://trybold.org)
          %tr
            %td External Image
            %td ![Alt text](http://...)
          %tr
            %td Lists
            %td
              = "- List item"
              %br/
              (indent by two spaces for nested lists)
          %tr
            %td Numbered Lists
            %td 1. List item
          %tr
            %td Blockquote
            %td &gt; quote
          %tr
            %td Headline
            %td # Headline
          %tr
            %td Headline 2nd level
            %td ## Headline
          %tr
            %td Headline 3rd level
            %td ### Headline
          %tr
            %td Abbreviations
            %td *[ISS]: International Space Station
          %tr
            %td Footnotes
            %td
              Text with a footnote[^1].
              %br
              [^1]: Here is the definition

      %p=raw t '.more', link: link_to( t('.link'), 'http://kramdown.gettalong.org/quickref.html', target: '_blank')

app/views/bold/content/_publish_status.html.haml
%small
  - if content.new_record?
    = t '.state.new'
  - else
    = t ".state.#{content.status}", date: l_date_time(content.post_date)
  - if content.last_update
    = t '.last_updated_on', date: l_date_time(content.last_update)
  - elsif content.updated_at && l_date_time(content.updated_at) != l_date_time(content.post_date)
    = t '.last_saved', date: l_date_time(content.updated_at)
  - if content.has_draft?
    = t '.draft_info', date: l_date_time(content.draft.updated_at)
    = link_to t('.view_diff'), diff_path(@content), remote: true

  = hidden_field_tag 'do_publish', '', id: 'do_publish'
  = hidden_field_tag 'go_back', '', id: 'go_back'

app/views/bold/content/_stats.html.haml
- if content.published?
  %br/
  - if count = content.desktop_hits
    %span{title: t('.desktop_hits')}
      = icon(:home)
      = count
  - if count = content.mobile_hits
    %span{title: t('.mobile_hits')}
      = icon(:phone)
      = count
  - if content.comments?
    %a{href: '#comments', title: t('.comments')}
      = icon(:comment)
      = content.comment_count

app/views/bold/content/_theme_variable_string.html.haml
= f.input "variables[#{name}]", as: :string, label: label

app/views/bold/content/_theme_variables.html.haml
- @content.variables.each do |name, kind|
  = render "bold/content/theme_variable_#{kind}", f: f, name: name, label: theme_text("variables.#{name}")

app/views/bold/content/_update.js.erb
<% @content.reload %>
<% if @success %>
  <% if @back_to %>
    window.location.href = '<%= escape_javascript @back_to %>';
  <% else %>
    $('#publish-status').html('<%= escape_javascript render 'bold/content/publish_status', content: @content %>');
    $('#other-actions').html('<%= escape_javascript render 'bold/content/delete_or_unpublish' %>');
    <% if @content.published? %>
      $('#pubdate-field').remove();
    <% end %>
    <% if @content.has_unpublished_changes? %>
      $('button[name=publish]').removeClass('has-no-draft').addClass('has-draft').attr('disabled', false);
    <% else %>
      $('button[name=publish]').addClass('has-no-draft').removeClass('has-draft').attr('disabled', true);
    <% end %>
    $('button[name=save]').attr('disabled', true);
    $('#change-template').attr('disabled', false);
    window.boldEditor.initDirty($('#bold-editor-form'));
  <% end %>
<% end %>

<%= raw flash_message unless @back_to %>

app/views/bold/content/diff.js.erb
$('#modal').html('<%= escape_javascript render 'bold/content/diff' %>').modal({backdrop: 'static'});