config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'frontend/contents#show'

  # To separate the backend from public sites, we wrap it with a constraint
  # that only allows access via a pre-configured 'backend_host'. See
  # config/bold.yml.sample for how to set that.
  #
  # Besides making the backend accessible exclusively via a dedicated hostname
  # (i.e. cms.yoursite.com) this has the nice side effect of freeing up the URL
  # name space for your sites so you dont have to worry about collisions with
  # Bold's backend.
  #
  # If you don't care about this kind of separation, set backend_host to your
  # sites public hostname. Your site will then redirect requests to backend
  # paths to Bold's login page instead of rendering the 404 page.
  #
  constraints Bold::Routes::BackendConstraint.new do

    devise_for :users

    # initial setup
    # the constraint hides these routes once at least one site is present.
    constraints Bold::Routes::SetupConstraint.new do
      namespace :setup do
        root 'users#new', as: 'root'
        resource :user, only: %i(new create)
        resource :site, only: %i(new create)
      end
    end

    # backend
    namespace :bold do

      root to: 'sites#index', as: :root

      resource :profile, only: %i(edit update edit_password update_password edit_email update_email) do
        collection do
          get :edit_email, :edit_password
          put :update_email, :update_password
        end
      end


      resources :sites, only: %i(show index)  do

        namespace :activity do
          resources :stats, only: :index do
            collection do
              get :visits_per_day
            end
          end
          resources :comments, shallow: true, only: %i(index destroy) do
            member do
              patch :restore, :mark_spam, :mark_ham, :approve, :unapprove
            end
            collection do
              delete :destroy_spam
            end
          end
        end

        resources :asset_links, only: :new

        resources :assets, shallow: true do
          collection do
            post :create_from_url
            get :gallery
            delete :bulk_destroy
          end
          member do
            post :pick
          end
        end
        resources :pages, shallow: true do
          member do
            get :diff, :change_template
            patch :update_template
            delete :delete_draft
          end
        end
        resources :posts, shallow: true do
          member do
            get :diff, :change_template
            patch :update_template
            delete :delete_draft
          end
        end

        # Site Settings
        namespace :settings do
          root 'settings#edit', as: 'root'

          resources :backups, only: %i(index create)
          resources :categories, shallow: true
          resources :tags, shallow: true, only: %i(index edit update destroy)

          resources :navigations, shallow: true, only: %i(index create update destroy) do
            collection{ put :sort }
          end

          resources :plugins, only: %i(index edit update enable destroy) do
            member{ put :enable }
          end

          resource :settings, only: %i(edit update favicon set_favicon) do
            member do
              get :favicon
              get :logo
            end
          end

          resource :html_snippet, only: %i(edit update)

          resources :site_users do
            member do
              put :resend_invitation
              delete :revoke_invitation
            end
          end

          resources :themes, only: %i(index edit update enable) do
            member{ put :enable }
          end
        end

        post 'undo/:id' => 'undo#create', as: :undo
      end

    end


    # global admin
    namespace :admin do

      resources :sites

      resources :users do
        collection do
          get :invited
          get :locked
        end
        member do
          put :lock
          put :unlock
          put :reset_password
        end
        resources :site_users, only: %i(new create edit update destroy)
      end

      resources :invitations, only: %i( index new create update destroy )

    end

  end # of BackendConstraint


  # Set up theme and plugin routes
  # While themes and plugins could just define their own routes via their own
  # config/routes.rb, these would end up after the catch all below and thus
  # never be reached. Instead, declare your routes when registering the
  # extension.
  Bold::Plugin.install_routes! self
  Bold::Theme.install_routes! self

  mount Ahoy::Engine => "/ahoy"

  # Frontend routes

  # retina support
  get 'displayconfig' => 'frontend/assets#display_config', as: :display_config

  # Sitemap
  get 'sitemap.xml' => 'frontend/sitemaps#show', as: :sitemap, defaults: { format: :xml }

  # site specific css / js
  get 'site' => 'frontend/site_contents#show', as: :site_content

  # Favicon
  get 'favicon.ico' => 'frontend/assets#favicon', as: :favicon

  # Assets
  get 'files/inline/:id(/:version)'    => 'frontend/assets#show',     as: :file
  get 'files/:id(/:version)/:filename' => 'frontend/assets#download', as: :download


  # Posts by Author
  get 'authors/:author' => 'frontend/contents#author', as: :author_posts, author: /.+/

  # redirect requests with single-digit months to 0x month format
  # to avoid duplicate content penalties
  get ':year/:month/*slug',
    constraints: { year: /\d{4}/, month: /\d/ },
    to: redirect('/%{year}/0%{month}/%{slug}')

  # Archive
  constraints year: /\d{4}/, month: /\d\d/ do
    get ':year(/:month)'      => 'frontend/contents#archive', as: :archive
  end

  # Contact message creation
  post 'contact/*path' => 'frontend/contact_messages#create', as: :contact_messages, format: false

  # Pages, Posts, Tags, Categories
  get  '*path' => 'frontend/contents#show',   as: :content, format: false
  # Comment creation
  post '*path' => 'frontend/comments#create', as: :comments, format: false

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/controllers/bold/settings/backups_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
class Bold::Settings::BackupsController < Bold::SettingsController
  def index
  end
end

app/controllers/bold/settings/categories_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
class Bold::Settings::CategoriesController < Bold::SettingsController
  helper 'bold/settings'

  prepend_before_action :find_category, only: %i(edit update destroy)
  site_object :category

  def index
    @categories = current_site.categories
  end

  def edit
  end

  def update
    r = UpdateCategory.call @category, category_params
    if r.category_updated?
      redirect_to bold_site_settings_categories_path(current_site)
    else
      render 'edit'
    end
  end

  def new
    @category = Category.new
  end

  def create
    r = CreateCategory.call(category_params)
    if r.category_created?
      redirect_to bold_site_settings_categories_path(current_site)
    else
      @category = r.category
      render 'new'
    end
  end

  def destroy
    memento(undo_template: 'restore_category') { @category.destroy }
    redirect_to bold_site_settings_categories_path(current_site), notice: 'bold.category.deleted'
  end


  private

  def find_category
    @category = Category.find params[:id]
  end

  def category_params
    params.require(:category).permit :name, :slug, :asset_id, :description
  end

end

app/controllers/bold/settings/html_snippets_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
class Bold::Settings::HtmlSnippetsController < Bold::Settings::SettingsController

  def edit
    @site = current_site
  end

  def update
    @site = current_site
    if @site.update_attributes(site_params)
      redirect_to edit_bold_site_settings_html_snippet_path(@site), notice: :saved
    else
      render 'edit'
    end
  end

end

app/controllers/bold/settings/navigations_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
class Bold::Settings::NavigationsController < Bold::SettingsController
  helper 'bold/settings'

  prepend_before_action :find_navigation, only: %i(update destroy sort)
  site_object :navigation

  def index
    @navigations = current_site.navigations
    @navigation = Navigation.new url: current_site.external_url
  end

  def create
    @navigation = current_site.navigations.build navigation_params
    if @navigation.save
      @navigation.move_to_bottom
      flash.now[:notice] = 'bold.navigation.created'
    end
  end

  def update
    @navigation.update_attributes navigation_params
    flash.now[:notice] = 'bold.navigation.updated'
  end

  def destroy
    Navigation.transaction do
      memento(undo_template: 'restore_navigation') do
        # prevent 'holes' in position list to make the client-side JS simpler
        @navigation.move_to_bottom
        @navigation.destroy
      end
    end
    flash.now[:notice] = 'bold.navigation.deleted'
  end

  def sort
    # jquery sortable is zero based, while with acts_as_list the first index
    # is 1:
    @navigation.insert_at params[:new_position].to_i + 1
    head :ok
  end

  private

  def find_navigation
    @navigation = Navigation.find params[:id]
  end

  def navigation_params
    params[:navigation].permit :name, :url
  end

end

app/controllers/bold/settings/tags_controller.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
class Bold::Settings::TagsController < Bold::SettingsController
  helper 'bold/settings'

  prepend_before_action :find_tag, only: %i(edit update destroy)
  site_object :tag

  def index
    @tags = current_site.tags.page(params[:page]).per(20)
  end

  def edit
  end

  def update
    r = UpdateTag.call @tag, tag_params
    if r.tag_updated?
      redirect_to bold_site_settings_tags_path(current_site)
    else
      render 'edit'
    end
  end

  def destroy
    DeleteTag.call @tag
    redirect_to bold_site_settings_tags_path(current_site), notice: 'bold.tag.deleted'
  end


  private

  def find_tag
    @tag = Tag.find params[:id]
  end

  def tag_params
    params.require(:tag).permit :name, :slug
  end

end

app/helpers/bold/settings/backups_helper.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold
  module Settings
    module BackupsHelper
    end
  end
end

app/helpers/bold/settings/site_users_helper.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold
  module Settings
    module SiteUsersHelper
    end
  end
end

app/helpers/bold/settings/themes_helper.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold
  module Settings
    module ThemesHelper
    end
  end
end

app/helpers/bold/settings_helper.rb
#
# Bold - more than just blogging.
# Copyright (C) 2015-2016 Jens Krämer <jk@jkraemer.net>
#
# This file is part of Bold.
#
# Bold is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Bold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Bold.  If not, see <http://www.gnu.org/licenses/>.
#
module Bold
  module SettingsHelper
    def render_extension_config(extension, args = {})
      if extension.configurable?
        begin
          return render args.merge(partial: extension.settings_partial)
        rescue ActionView::MissingTemplate
        end
      end
      return content_tag(:p, I18n.t('bold.extensions.no_config'))
    end

    def pages_for(usage)
      @site.pages.published.order('title ASC').select do |page|
        ::Bold::Template::USAGE_KEYS[usage].include? page.get_template.usage
      end
    end
  end
end

app/views/bold/settings/settings/_edit.html.haml
.row
  .col-sm-9.col-sm-offset-1.col-md-8.col-lg-7

    %h2= t '.heading'

    = simple_form_for @site, url: bold_site_settings_settings_path(current_site) do |f|

      = f.input :name, input_html: { class: 'input-lg' }
      .row
        .col-sm-3
          = f.input :url_scheme, collection: %w(https http), value_method: :to_s, label_method: :to_s, include_blank: false
        .col-sm-9
          = f.input :hostname, placeholder: t('.hostname_plh')
      = f.input :alias_string

      .row
        .col-sm-3
          .form-group
            %label.control-label= t'.favicon'
            %div.favicon
              - if @site.favicon
                = link_to image_tag(bold_asset_path(@site.favicon), alt: 'favicon'), favicon_bold_site_settings_settings_path(current_site), remote: true
                &nbsp;
                = link_to t('.change'), favicon_bold_site_settings_settings_path(current_site), remote: true, class: 'btn btn-default btn-sm'
              - else
                = link_to t('.set_favicon'), favicon_bold_site_settings_settings_path(current_site), remote: true, class: 'btn btn-default btn-sm'

        .col-sm-9
          .form-group
            %label.control-label= t'.logo'
            %div.logo
              - if @site.logo
                = link_to image_tag(bold_asset_path(@site.logo), alt: 'logo'), logo_bold_site_settings_settings_path, remote: true
                &nbsp;
                = link_to t('.change'), logo_bold_site_settings_settings_path(current_site), remote: true, class: 'btn btn-default btn-sm'
              - else
                = link_to t('.set_favicon'), logo_bold_site_settings_settings_path(current_site), remote: true, class: 'btn btn-default btn-sm'

      = f.input :twitter_handle, hint: t('.twitter_hint')

      = f.input :honor_donottrack, as: :boolean, wrapper: :vertical_boolean
      = f.input :adaptive_images,   as: :boolean, wrapper: :vertical_boolean, hint: t('.adaptive_images_hint')

      %fieldset
        %legend= t '.legend.i18n'
        .row
          .col-sm-6
            = f.input :default_locale, collection: languages_for_select(@site.available_locales), value_method: :last, label_method: :first, include_blank: false
          .col-sm-6
            = f.input :detect_user_locale, as: :boolean, wrapper: :vertical_boolean

        .row
          .col-sm-6
            = f.input :time_zone_name


      %fieldset
        %legend= t '.legend.pages'

        .row
          .col-sm-6
            = f.input :homepage_id, collection: pages_for(:homepage), value_method: :to_param, label_method: :title, include_blank: false
          .col-sm-6
            = f.input :search_page_id, collection: pages_for(:search), value_method: :to_param, label_method: :title, include_blank: true
        .row
          .col-sm-6
            = f.input :tag_page_id, collection: pages_for(:tag), value_method: :to_param, label_method: :title, include_blank: true
          .col-sm-6
            = f.input :category_page_id, collection: pages_for(:category), value_method: :to_param, label_method: :title, include_blank: true
        .row
          .col-sm-6
            = f.input :author_page_id, collection: pages_for(:author), value_method: :to_param, label_method: :title, include_blank: true
          .col-sm-6
            = f.input :archive_page_id, collection: pages_for(:archive), value_method: :to_param, label_method: :title, include_blank: true
        .row
          .col-sm-6
            = f.input :notfound_page_id, collection: pages_for(:not_found), value_method: :to_param, label_method: :title, include_blank: true
          .col-sm-6
            = f.input :error_page_id, collection: pages_for(:error), value_method: :to_param, label_method: :title, include_blank: true


      %fieldset
        %legend= t '.legend.comments'

        .row
          .col-sm-6
            = f.input :post_comments, collection: comment_options, value_method: :first, label_method: :last, include_blank: t('admin.sites.edit.comments.disabled')
        .row
          .col-sm-12
            = f.input :akismet_key, hint: t('.akismet_key_hint')


      .buttons
        = button

app/views/bold/settings/settings/_favicon.html.haml
.modal-dialog.modal-lg.big
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h4#modal-label.modal-title= t '.heading'

    .modal-body

      .row
        - if @assets.blank?
          .col-xs-12
            %p
              = t'.no_possible_icons'
              = link_to t('.upload'), new_bold_site_asset_path(current_site) , class: 'btn btn-default'
        - else
          - for asset in @assets
            .col-xs-2
              .thumbnail
                = link_to asset_tag(asset, :bold_thumb), bold_site_settings_settings_path(current_site, site: { favicon_id: asset.id }), method: :put, title: asset.filename
                .caption
                  = asset.filename
                  - if asset.title.present?
                    %br/
                    = asset.title
                  %br/
                  = number_to_human_size asset.file_size
                  %br/
                  = l_date_time asset.created_at

    .modal-footer
      = bold_pagination_for @assets, remote: true

app/views/bold/settings/settings/_image_picker.html.haml
.modal-dialog.modal-lg.big
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h4#modal-label.modal-title= t '.heading'

    .modal-body

      .row
        - if @assets.blank?
          .col-xs-12
            %p
              = t'.no_possible_files'
              = link_to t('.upload'), new_bold_site_asset_path(current_site) , class: 'btn btn-default'
        - else
          - for asset in @assets
            .col-xs-2
              .thumbnail
                = link_to asset_tag(asset, :bold_thumb), take_url.call(asset), method: :put, title: asset.filename
                .caption
                  = asset.filename
                  - if asset.title.present?
                    %br/
                    = asset.title
                  %br/
                  = number_to_human_size asset.file_size
                  %br/
                  = l_date_time asset.created_at

    .modal-footer
      = bold_pagination_for @assets, remote: true

app/views/bold/settings/settings/_logo.html.haml
= render 'image_picker', take_url: ->(asset) { bold_settings_settings_path(site: { logo_id: asset.id }) }

app/views/bold/settings/settings/edit.html.haml
.row
  = render 'bold/settings/left_col'

  .col-xs-12.col-sm-9.right-col
    = render 'edit'

app/views/bold/settings/settings/favicon.js.erb
<%= open_modal 'favicon' %>

app/views/bold/settings/settings/logo.js.erb
<%= open_modal 'logo' %>